name: Fetch new changelogs for main & deploy gh-pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  "32 6,18 * * *"

jobs:
  fetch_merges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Update rails
        run: git submodule init && git submodule update && cd rails && git fetch
      - name: bin/fetch_merges
        run: bin/fetch_merges

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install

      - name: Build
        run: bin/bridgetown deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
