name: Fetch new changelogs

on:
  push:
    branches:
      - main
  schedule:
    - cron:  "32 6,18 * * *"

jobs:
  fetch_merges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Update rails submodule
        run: git submodule init && git submodule update && cd rails && git pull origin main

      - name: bin/fetch_merges
        run: bin/fetch_merges

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "Auto: add new changelog items"
